# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0003_auto_20160624_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='title',
            field=models.ForeignKey(blank=True, help_text=b"Optional title to appear before reporter's name.", null=True, on_delete=django.db.models.deletion.CASCADE, to='checkup.Title'),
        ),
    ]
